set(_AMENT_PACKAGE_NAME "aqua_interfaces")
set(aqua_interfaces_VERSION "0.0.0")
set(aqua_interfaces_MAINTAINER "woody <woody.myung@gmail.com>")
set(aqua_interfaces_BUILD_DEPENDS "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(aqua_interfaces_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(aqua_interfaces_BUILD_EXPORT_DEPENDS "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(aqua_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(aqua_interfaces_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(aqua_interfaces_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(aqua_interfaces_GROUP_DEPENDS )
set(aqua_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(aqua_interfaces_DEPRECATED "")
set(aqua_interfaces_EXPORT_TAGS)
list(APPEND aqua_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
